AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application example.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://rencinas-bucket2/152e910ffbe5d73088ef37a27ab47748
      Handler: org.example.handlers.FirstHandler
      FunctionName: REFirstFunction
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
