AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application example.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://smm-springboot/b4a3196151babbc3cc43bfcffc1fce10
      Handler: org.example.handlers.HandlerRequest
      FunctionName: basic-lambda-smm
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
