AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application example.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/Lambda-Athena-final-project1-1.0-SNAPSHOT.zip
      Handler: org.example.handlers.HandlerRequest
      FunctionName: cvillalba-aclavijo-final-project1
      Runtime: java11
      Description: Java function
      MemorySize: 1024
      Timeout: 15

      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonAthenaFullAccess
        - AmazonS3ReadOnlyAccess
      Tracing: Active