AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application example.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://practice-backend-aclavijo/95591b2d9bf20b4ae01144b9a9ad5564
      Handler: org.example.handlers.FirstHandler
      FunctionName: practice-aclavijo-lambda1
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - LambdaInvokePolicy:
          FunctionName: practice-aclavijo-lambda2
      - AmazonAthenaFullAccess
      Tracing: Active
